classification:
- segment: ST
  field: ST01
  severity: hard
  ignore_case: false
  numeric: false
- segment: ST
  field: ST02
  severity: hard
  ignore_case: false
  numeric: false
- segment: ST
  field: ST03
  severity: soft
  ignore_case: false
  numeric: false
- segment: B2
  field: B201
  severity: soft
  ignore_case: false
  numeric: false
- segment: B2
  field: B202
  severity: soft
  ignore_case: false
  numeric: false
- segment: B2
  field: B203
  severity: soft
  ignore_case: false
  numeric: false
- segment: B2
  field: B204
  severity: soft
  ignore_case: false
  numeric: false
- segment: B2
  field: B205
  severity: soft
  ignore_case: false
  numeric: false
- segment: B2
  field: B206
  severity: hard
  ignore_case: false
  numeric: false
- segment: B2
  field: B207
  severity: soft
  ignore_case: false
  numeric: false
- segment: B2
  field: B208
  severity: soft
  ignore_case: false
  numeric: false
- segment: B2
  field: B209
  severity: soft
  ignore_case: false
  numeric: false
- segment: B2
  field: B210
  severity: soft
  ignore_case: false
  numeric: false
- segment: B2
  field: B211
  severity: soft
  ignore_case: false
  numeric: false
- segment: B2
  field: B212
  severity: soft
  ignore_case: false
  numeric: false
- segment: B2A
  field: B2A01
  severity: hard
  ignore_case: false
  numeric: false
- segment: B2A
  field: B2A02
  severity: soft
  ignore_case: false
  numeric: false
- segment: C3
  field: C301
  severity: soft
  ignore_case: false
  numeric: false
- segment: C3
  field: C302
  severity: soft
  ignore_case: false
  numeric: false
- segment: C3
  field: C303
  severity: soft
  ignore_case: false
  numeric: false
- segment: C3
  field: C304
  severity: soft
  ignore_case: false
  numeric: false
- segment: L11
  field: L1101
  severity: soft
  ignore_case: false
  numeric: false
- segment: L11
  field: L1102
  severity: soft
  ignore_case: false
  numeric: false
- segment: L11
  field: L1103
  severity: soft
  ignore_case: false
  numeric: false
- segment: L11
  field: L1104
  severity: soft
  ignore_case: false
  numeric: false
- segment: L11
  field: L1105
  severity: soft
  ignore_case: false
  numeric: false
- segment: G62
  field: G6201
  severity: soft
  ignore_case: false
  numeric: false
- segment: G62
  field: G6202
  severity: soft
  ignore_case: false
  numeric: false
- segment: G62
  field: G6203
  severity: soft
  ignore_case: false
  numeric: false
- segment: G62
  field: G6204
  severity: soft
  ignore_case: false
  numeric: false
- segment: G62
  field: G6205
  severity: soft
  ignore_case: false
  numeric: false
- segment: MS3
  field: MS301
  severity: soft
  ignore_case: false
  numeric: false
- segment: MS3
  field: MS302
  severity: soft
  ignore_case: false
  numeric: false
- segment: MS3
  field: MS303
  severity: soft
  ignore_case: false
  numeric: false
- segment: MS3
  field: MS304
  severity: soft
  ignore_case: false
  numeric: false
- segment: MS3
  field: MS305
  severity: soft
  ignore_case: false
  numeric: false
- segment: PLD
  field: PLD01
  severity: soft
  ignore_case: false
  numeric: false
- segment: PLD
  field: PLD02
  severity: soft
  ignore_case: false
  numeric: false
- segment: PLD
  field: PLD03
  severity: soft
  ignore_case: false
  numeric: false
- segment: PLD
  field: PLD04
  severity: soft
  ignore_case: false
  numeric: false
- segment: LH6
  field: LH601
  severity: soft
  ignore_case: false
  numeric: false
- segment: LH6
  field: LH602
  severity: soft
  ignore_case: false
  numeric: false
- segment: LH6
  field: LH603
  severity: soft
  ignore_case: false
  numeric: false
- segment: LH6
  field: LH604
  severity: soft
  ignore_case: false
  numeric: false
- segment: NTE
  field: NTE01
  severity: soft
  ignore_case: false
  numeric: false
- segment: NTE
  field: NTE02
  severity: soft
  ignore_case: false
  numeric: false
- segment: L3
  field: L301
  severity: soft
  ignore_case: false
  numeric: false
- segment: L3
  field: L302
  severity: soft
  ignore_case: false
  numeric: false
- segment: L3
  field: L303
  severity: soft
  ignore_case: false
  numeric: false
- segment: L3
  field: L304
  severity: soft
  ignore_case: false
  numeric: false
- segment: L3
  field: L305
  severity: soft
  ignore_case: false
  numeric: false
- segment: L3
  field: L306
  severity: soft
  ignore_case: false
  numeric: false
- segment: L3
  field: L307
  severity: soft
  ignore_case: false
  numeric: false
- segment: L3
  field: L308
  severity: soft
  ignore_case: false
  numeric: false
- segment: L3
  field: L309
  severity: soft
  ignore_case: false
  numeric: false
- segment: L3
  field: L310
  severity: soft
  ignore_case: false
  numeric: false
- segment: L3
  field: L311
  severity: soft
  ignore_case: false
  numeric: false
- segment: L3
  field: L312
  severity: soft
  ignore_case: false
  numeric: false
- segment: L3
  field: L313
  severity: soft
  ignore_case: false
  numeric: false
- segment: L3
  field: L314
  severity: soft
  ignore_case: false
  numeric: false
- segment: L3
  field: L315
  severity: soft
  ignore_case: false
  numeric: false
- segment: SE
  field: SE01
  severity: hard
  ignore_case: false
  numeric: false
- segment: SE
  field: SE02
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: '*'
  severity: hard
  ignore_case: false
  numeric: false
ignore: []
