classification:
- segment: ST
  field: ST01
  severity: hard
  ignore_case: false
  numeric: false
- segment: ST
  field: ST02
  severity: hard
  ignore_case: false
  numeric: false
- segment: B10
  field: B1001
  severity: soft
  ignore_case: false
  numeric: false
- segment: B10
  field: B1002
  severity: soft
  ignore_case: false
  numeric: false
- segment: B10
  field: B1003
  severity: hard
  ignore_case: false
  numeric: false
- segment: B10
  field: B1004
  severity: soft
  ignore_case: false
  numeric: false
- segment: B10
  field: B1005
  severity: soft
  ignore_case: false
  numeric: false
- segment: B10
  field: B1006
  severity: soft
  ignore_case: false
  numeric: false
- segment: B10
  field: B1007
  severity: soft
  ignore_case: false
  numeric: false
- segment: L11
  field: L1101
  severity: soft
  ignore_case: false
  numeric: false
- segment: L11
  field: L1102
  severity: soft
  ignore_case: false
  numeric: false
- segment: L11
  field: L1103
  severity: soft
  ignore_case: false
  numeric: false
- segment: MAN
  field: MAN01
  severity: soft
  ignore_case: false
  numeric: false
- segment: MAN
  field: MAN02
  severity: soft
  ignore_case: false
  numeric: false
- segment: MAN
  field: MAN03
  severity: soft
  ignore_case: false
  numeric: false
- segment: MAN
  field: MAN04
  severity: soft
  ignore_case: false
  numeric: false
- segment: MAN
  field: MAN05
  severity: soft
  ignore_case: false
  numeric: false
- segment: MAN
  field: MAN06
  severity: soft
  ignore_case: false
  numeric: false
- segment: K1
  field: K101
  severity: soft
  ignore_case: false
  numeric: false
- segment: K1
  field: K102
  severity: soft
  ignore_case: false
  numeric: false
- segment: MS3
  field: MS301
  severity: soft
  ignore_case: false
  numeric: false
- segment: MS3
  field: MS302
  severity: soft
  ignore_case: false
  numeric: false
- segment: MS3
  field: MS303
  severity: soft
  ignore_case: false
  numeric: false
- segment: MS3
  field: MS304
  severity: soft
  ignore_case: false
  numeric: false
- segment: MS3
  field: MS305
  severity: soft
  ignore_case: false
  numeric: false
- segment: SE
  field: SE01
  severity: hard
  ignore_case: false
  numeric: false
- segment: SE
  field: SE02
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: '*'
  severity: hard
  ignore_case: false
  numeric: false
ignore: []
