classification:
- segment: ST
  field: ST01
  severity: hard
  ignore_case: false
  numeric: false
- segment: ST
  field: ST02
  severity: hard
  ignore_case: false
  numeric: false
- segment: B1
  field: B101
  severity: soft
  ignore_case: false
  numeric: false
- segment: B1
  field: B102
  severity: hard
  ignore_case: false
  numeric: false
- segment: B1
  field: B103
  severity: soft
  ignore_case: false
  numeric: false
- segment: B1
  field: B104
  severity: soft
  ignore_case: false
  numeric: false
- segment: N9
  field: N901
  severity: soft
  ignore_case: false
  numeric: false
- segment: N9
  field: N902
  severity: soft
  ignore_case: false
  numeric: false
- segment: N9
  field: N903
  severity: soft
  ignore_case: false
  numeric: false
- segment: N9
  field: N904
  severity: soft
  ignore_case: false
  numeric: false
- segment: N9
  field: N905
  severity: soft
  ignore_case: false
  numeric: false
- segment: N9
  field: N906
  severity: soft
  ignore_case: false
  numeric: false
- segment: N9
  field: N907
  severity: soft
  ignore_case: false
  numeric: false
- segment: G62
  field: G6201
  severity: soft
  ignore_case: false
  numeric: false
- segment: G62
  field: G6202
  severity: soft
  ignore_case: false
  numeric: false
- segment: G62
  field: G6203
  severity: soft
  ignore_case: false
  numeric: false
- segment: G62
  field: G6204
  severity: soft
  ignore_case: false
  numeric: false
- segment: G62
  field: G6205
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N701
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N702
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N703
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N704
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N705
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N706
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N707
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N708
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N709
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N710
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N711
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N712
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N713
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N714
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N715
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N716
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N717
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N718
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N719
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N720
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N721
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N722
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N723
  severity: soft
  ignore_case: false
  numeric: false
- segment: N7
  field: N724
  severity: soft
  ignore_case: false
  numeric: false
- segment: L9
  field: L901
  severity: soft
  ignore_case: false
  numeric: false
- segment: L9
  field: L902
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V901
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V902
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V903
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V904
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V905
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V906
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V907
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V908
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V909
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V910
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V911
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V912
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V913
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V914
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V915
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V916
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V917
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V918
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V919
  severity: soft
  ignore_case: false
  numeric: false
- segment: V9
  field: V920
  severity: soft
  ignore_case: false
  numeric: false
- segment: K1
  field: K101
  severity: soft
  ignore_case: false
  numeric: false
- segment: K1
  field: K102
  severity: soft
  ignore_case: false
  numeric: false
- segment: SE
  field: SE01
  severity: hard
  ignore_case: false
  numeric: false
- segment: SE
  field: SE02
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: '*'
  severity: hard
  ignore_case: false
  numeric: false
ignore: []
