classification:
- segment: '*'
  field: InvoiceAmount
  severity: hard
  ignore_case: false
  numeric: true
  conditional_qualifier: null
  amount_variance: null
- segment: '*'
  field: WeightShipped
  severity: hard
  ignore_case: false
  numeric: true
  conditional_qualifier: null
  amount_variance: null
- segment: '*'
  field: UnitPrice
  severity: hard
  ignore_case: false
  numeric: true
  conditional_qualifier: null
  amount_variance: null
- segment: '*'
  field: QuantityShipped
  severity: hard
  ignore_case: false
  numeric: true
  conditional_qualifier: null
  amount_variance: null
- segment: '*'
  field: Discount
  severity: hard
  ignore_case: false
  numeric: true
  conditional_qualifier: null
  amount_variance: null
- segment: '*'
  field: Taxes
  severity: hard
  ignore_case: false
  numeric: true
  conditional_qualifier: null
  amount_variance: null
- segment: '*'
  field: ExtendedPrice
  severity: hard
  ignore_case: false
  numeric: true
  conditional_qualifier: null
  amount_variance: null
- segment: '*'
  field: ProductDescription
  severity: soft
  ignore_case: true
  numeric: false
  conditional_qualifier: null
  amount_variance: null
- segment: '*'
  field: GTIN
  severity: ignore
  ignore_case: false
  numeric: false
ignore: []
