classification:
- segment: '*'
  field: PurchaseOrderNumber
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: InvoiceID
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: InvoiceAmount
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: CustomerCode
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: InvoiceDate
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: DueDate
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: ProductDescription
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: DistributorProductID
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: GTIN
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: UnitofMeasure
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: Pack
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: Size
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: WeightShipped
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: UnitPrice
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: QuantityShipped
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: Discount
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: Taxes
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: ExtendedPrice
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: '*'
  severity: hard
  ignore_case: false
  numeric: false
ignore: []
