classification:
- segment: '*'
  field: recordID
  severity: ignore
  ignore_case: false
  numeric: false
- segment: '*'
  field: allowChargeIndicator
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: allowChargeCode
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: percentQualifier
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: percent
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: ignore
  severity: ignore
  ignore_case: false
  numeric: false
- segment: '*'
  field: allowChargeHandlingCode
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: referenceID
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: orderGuideCategory
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: orderGuideCategoryDes
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: allowChargeDesc
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: tPCode
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: functionalGroupCode
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: messageID
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: messageClass
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: companyNumber
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: divisionNumber
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: departmentNumber
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: warehouseNumber
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: customerNumber
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: referenceQualifier
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: termsTypeCode
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: termsDiscountPercent
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: termsDiscountDueDate
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: termsDiscountDays
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: termsDiscountAmount
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: termsNetDueDate
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: termsNetDays
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: termsDescription
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: shipMethodOfPayment
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: transportationType
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: orderContractNumber
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: contractNumber
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: manifestNumber
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: orderNumber
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: invoiceNumber
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: orderDate
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: invoiceDate
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: shipDate
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: pONumber
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: billOfLadingNumber
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: aPVendorNumber
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: marketingVendorNumber
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: creditDebitCode
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: originalInvoiceNumber
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: shipToName
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: shipToIDQualifier
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: shiptoID
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: shipToStoreNumber
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: shipToCustomerNumber
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: customerLangPref
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: chainDescription
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: shipToCity
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: shipToProvince
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: shipToPostalCode
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: billToName
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: billToIDQualifier
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: billToID
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: remitToName
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: remitToIDQualifier
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: remitToID
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: shiptoAddress1
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: shiptoAddress2
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: billToAddress1
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: billToCareOf
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: billToCity
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: billToProvince
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: billToPostalCode
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: remitToCity
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: remitToProvince
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: remitToPostalCode
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: itemDescription
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: lineNumber
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: distributorItemNumber
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: uPCQualifier
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: uPCEANNumber
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: customerItemNumber
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: unitOfMeasure
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: itemsPerUnit
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: taxes
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: catchWeightFlag
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: BrokenCaseCode
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: itemNonStockIndicator
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: quantityOrdered
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: quantityShipped
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: quantityDifference
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: lotNumber
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: productionDayCodeSubCode
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: priceQuantity
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: priceUnitOfMeasure
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: unitGrossWeight
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: unitNetWeight
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: remitToAddress
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: remitToCareOf
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: vendorNumber
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: vendorName
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: vendorItemNumber
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: classNumber
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: classDescription
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: priceBookHeading
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: pricebookHeadingDescription
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: priceBookFamilyNumber
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: priceBookFamilyDescription
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: brand
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: pack
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: size
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: servingsPerCase
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: servingsPerCaseUOM
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: caseUPCNumber
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: vendorUPCNumber
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: unitUPCNumber
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: lineCount
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: itemCount
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: totalWeight
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: extendedFeeAmount
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: extendedDiscountAmount
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: extendedInventoryTax
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: bottleDeposit
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: netInvoiceAmout
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: originalOrderDate
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: originalOrderNumber
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: originalInvoiceDate
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: extraItemDescription2
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: extraItemDescription3
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: vendorPhoneNumber
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: taxPercntCode
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: taxPercntage
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: taxPrcentCode
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: taxPrcntage
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: taxPercentCode
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: taxPercentage
  severity: hard
  ignore_case: false
  numeric: true
- segment: '*'
  field: SAPWarehouseNumber
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: creditCode
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: creditCodeDescription
  severity: soft
  ignore_case: true
  numeric: false
- segment: '*'
  field: '*'
  severity: hard
  ignore_case: false
  numeric: false
ignore: []
