classification:
- segment: BEG
  field: BEG03
  severity: hard
  ignore_case: false
  numeric: false
- segment: BEG
  field: BEG05
  severity: hard
  ignore_case: false
  numeric: false
- segment: ISA
  field: ISA06
  severity: hard
  ignore_case: false
  numeric: false
- segment: ISA
  field: ISA08
  severity: hard
  ignore_case: false
  numeric: false
- segment: PO1
  field: PO101
  severity: hard
  ignore_case: false
  numeric: false
- segment: PO1
  field: PO102
  severity: hard
  ignore_case: false
  numeric: false
- segment: PO1
  field: PO104
  severity: hard
  ignore_case: false
  numeric: false
- segment: PO1
  field: PO107
  severity: hard
  ignore_case: false
  numeric: false
- segment: '*'
  field: '*'
  severity: hard
  ignore_case: false
  numeric: false
ignore: []
